<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <Version>$(SerdeMsgPackPkgVersion)</Version>
    <Description>MessagePack format support for Serde.NET.</Description>
    <Authors>Serde.NET</Authors>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/serdedotnet/serde.msgpack</PackageProjectUrl>
    <RepositoryUrl>https://github.com/serdedotnet/serde.msgpack</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serde" />
  </ItemGroup>

</Project>
